# Generated by Django 5.0.2 on 2024-03-05 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_image_alter_userprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
