# Generated by Django 5.0.2 on 2024-03-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_matchinfo_user1_alter_matchinfo_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='score_loser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='score_winner',
            field=models.IntegerField(default=0),
        ),
    ]
