# Generated by Django 5.0.1 on 2024-01-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_created_date_users_password_users_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='updated_date',
            new_name='updated',
        ),
    ]
